/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.eendroroy.gradle.remote

import java.io.File
import java.nio.file.Files
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder

/**
 * A simple functional test for the 'io.github.eendroroy.gradle.remote' plugin.
 */
class GradleRemotePluginFunctionalTest {
    @get:Rule val tempFolder = TemporaryFolder()

    private fun getProjectDir() = tempFolder.root
    private fun getBuildFile() = getProjectDir().resolve("build.gradle")
    private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")

    @Test fun `can run task`() {
        // Setup the test build
        getSettingsFile().writeText("")
        getBuildFile().writeText("""
plugins {
    id('io.github.eendroroy.gradle.remote')
}

remote {
    name = "no name"
    ip = "0.0.0.0"
}
""")

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("greeting")
        runner.withProjectDir(getProjectDir())
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'io.github.eendroroy.gradle.remote'"))
        assertTrue(result.output.contains("no name"))
        assertTrue(result.output.contains("0.0.0.0"))
    }
}
